from .auth import (
    JWT_BEARER_GRANT,
    ServiceKey,
    TokenManager,
    TokenSource,
    create_assertion,
)
from .circuit_breaker import CircuitState, ClientCircuitBreaker, origin_of
from .client import CsarTransport, create_csar_client
from .constants import (
    BACKPRESSURE_STATUS,
    ERROR_CODES,
    HEADER_AUTHORIZATION,
    HEADER_CLIENT_LIMIT,
    HEADER_PROTOCOL_VERSION,
    HEADER_RETRY_AFTER,
    HEADER_STATUS,
    HEADER_WAIT_MS,
    PROTOCOL_VERSION,
    STATUS_BACKPRESSURE,
    STATUS_CIRCUIT_HALF_OPEN,
    STATUS_CIRCUIT_OPEN,
    STATUS_THROTTLED,
)
from .dedup import RequestDeduplicator
from .errors import (
    AuthErrorCode,
    CsarAuthError,
    CsarBackpressureError,
    CsarCircuitBrokenError,
    CsarError,
)
from .extract import (
    ApiError,
    WaitSource,
    csar_status,
    get_header,
    parse_api_error,
    parse_retry_after,
    protocol_version,
    wait_time,
)
from .pipeline import (
    Handler,
    Middleware,
    PipelineTransport,
    auth_middleware,
    circuit_breaker_middleware,
    dedup_middleware,
    headers_middleware,
    retry_middleware,
)
from .trace import generate_request_id, generate_traceparent

__version__ = "0.1.0"

__all__ = [
    "BACKPRESSURE_STATUS",
    "ERROR_CODES",
    "HEADER_AUTHORIZATION",
    "HEADER_CLIENT_LIMIT",
    "HEADER_PROTOCOL_VERSION",
    "HEADER_RETRY_AFTER",
    "HEADER_STATUS",
    "HEADER_WAIT_MS",
    "JWT_BEARER_GRANT",
    "PROTOCOL_VERSION",
    "STATUS_BACKPRESSURE",
    "STATUS_CIRCUIT_HALF_OPEN",
    "STATUS_CIRCUIT_OPEN",
    "STATUS_THROTTLED",
    "ApiError",
    "AuthErrorCode",
    "CircuitState",
    "ClientCircuitBreaker",
    "CsarAuthError",
    "CsarBackpressureError",
    "CsarCircuitBrokenError",
    "CsarError",
    "CsarTransport",
    "Handler",
    "Middleware",
    "PipelineTransport",
    "RequestDeduplicator",
    "ServiceKey",
    "TokenManager",
    "TokenSource",
    "WaitSource",
    "__version__",
    "auth_middleware",
    "circuit_breaker_middleware",
    "create_assertion",
    "create_csar_client",
    "csar_status",
    "dedup_middleware",
    "generate_request_id",
    "generate_traceparent",
    "get_header",
    "headers_middleware",
    "origin_of",
    "parse_api_error",
    "parse_retry_after",
    "protocol_version",
    "retry_middleware",
    "wait_time",
]
