PROTOCOL_VERSION = 1

HEADER_WAIT_MS = "X-CSAR-Wait-MS"
HEADER_CLIENT_LIMIT = "X-CSAR-Client-Limit"
HEADER_STATUS = "X-CSAR-Status"
HEADER_PROTOCOL_VERSION = "X-CSAR-Protocol-Version"
HEADER_AUTHORIZATION = "X-Csar-Authorization"
HEADER_RETRY_AFTER = "Retry-After"
HEADER_REQUEST_ID = "X-Request-Id"
HEADER_TRACEPARENT = "traceparent"

BACKPRESSURE_STATUS = 503

STATUS_THROTTLED = "throttled"
STATUS_BACKPRESSURE = "backpressure"
STATUS_CIRCUIT_OPEN = "circuit_open"
STATUS_CIRCUIT_HALF_OPEN = "circuit_half_open"
CIRCUIT_STATUSES = frozenset({STATUS_CIRCUIT_OPEN, STATUS_CIRCUIT_HALF_OPEN})
KNOWN_STATUSES = frozenset({STATUS_THROTTLED, STATUS_BACKPRESSURE}) | CIRCUIT_STATUSES

ERROR_ROUTE_NOT_FOUND = "route_not_found"
ERROR_ACCESS_DENIED = "access_denied"
ERROR_AUTH_FAILED = "auth_failed"
ERROR_THROTTLED = "throttled"
ERROR_CIRCUIT_OPEN = "circuit_open"
ERROR_BACKPRESSURE = "backpressure"
ERROR_UPSTREAM = "upstream_error"
ERROR_NO_HEALTHY_UPSTREAM = "no_healthy_upstream"
ERROR_TENANT_NOT_FOUND = "tenant_not_found"
ERROR_RESPONSE_TOO_LARGE = "response_too_large"
ERROR_SECURITY = "security_error"
ERROR_CODES = frozenset({
    ERROR_ROUTE_NOT_FOUND,
    ERROR_ACCESS_DENIED,
    ERROR_AUTH_FAILED,
    ERROR_THROTTLED,
    ERROR_CIRCUIT_OPEN,
    ERROR_BACKPRESSURE,
    ERROR_UPSTREAM,
    ERROR_NO_HEALTHY_UPSTREAM,
    ERROR_TENANT_NOT_FOUND,
    ERROR_RESPONSE_TOO_LARGE,
    ERROR_SECURITY,
})

LEGACY_CIRCUIT_BODY_MARKER = b"circuit breaker open"
